src/Entity/Campus.php
<?php

namespace App\Entity;

use App\Repository\CampusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampusRepository::class)
 */
class Campus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="campus")
     */
    private $Sorties;

    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="campus")
     */
    private $Participants;

    public function __construct()
    {
        $this->Sorties = new ArrayCollection();
        $this->Participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->Sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->Sorties->contains($sorty)) {
            $this->Sorties[] = $sorty;
            $sorty->setCampus($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->Sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getCampus() === $this) {
                $sorty->setCampus(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->Participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->Participants->contains($participant)) {
            $this->Participants[] = $participant;
            $participant->setCampus($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->Participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getCampus() === $this) {
                $participant->setCampus(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\Sortie;
use App\Form\SearchType;
use App\Model\FiltreSortie;
use App\Repository\EtatRepository;
use App\Repository\SortieRepository;
use App\Repository\CampusRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route ("/main", name="main_")
 */
class MainController extends AbstractController
{

    /**
     * @Route("/", name="home")
     *
     */
    public function home(SortieRepository $sortieRespository,
                         CampusRepository $campusRepository,
                         Request          $request
    ): Response
    {

        $filtreSortie = new FiltreSortie();
        $filtreSortie->setCampus($this->getUser()->getCampus());
        $searchForm = $this->createForm(SearchType::class, $filtreSortie);
        $searchForm->handleRequest($request);
        $sorties = $sortieRespository->filtreEvent($filtreSortie, $this->getUser());

        $campus = $campusRepository->findAll();

        return $this->render('main/home.html.twig', [
            'sorties' => $sorties,
            'campus' => $campus,
            'searchForm' => $searchForm->createView()
        ]);

    }

    /**
     * @Route ("/main/sinscrire/{id}", name="sinscrire")
     *
     */
    public function inscription(EntityManagerInterface $em,
                                EtatRepository         $er,
                                int                    $id): Response
    {

        $sortie = $em->getRepository(Sortie::class)->find($id);
        if (!$sortie) {
            throw $this->createNotFoundException("Sortie non existante");
        }

        //Est ce que la sortie est publiée?
        $sortiePubliee = $sortie->getEtat()->getLibelle() === Etat::ouverte();

        //Est ce que les inscriptions sont ouvertes?
        $sortieOuverte = $sortie->getDateLimiteInscription() > new \DateTime('now');

        //Est ce qu'il reste de la place?
        $sortieRemplie = count($sortie->getParticipants()) < $sortie->getNbInscriptionsMax();

        $inscriptionDispo = $sortiePubliee && $sortieOuverte && $sortieRemplie;

        if ($inscriptionDispo) {
            $sortie->addParticipant($this->getUser());

            if (count($sortie->getParticipants()) >= $sortie->getNbInscriptionsMax()) {
                $sortie->setEtat($er->findOneBy(['libelle' => Etat::cloturee()]));
            }

            $em->persist($sortie);
            $em->flush();
            $this->addFlash('success', 'Votre inscription a bien été enregistrée ! ');
        } else {
            $this->addFlash('error', 'Impossible de s\'inscrire à l\'événement');
        }

        return $this->redirectToRoute('main_home');


    }

    /**
     * @Route("/main/desinscription/{id}", name="desinscription")
     */
    public function desinscription(EntityManagerInterface $entityManager,
                                   EtatRepository         $er,
                                   int                    $id): Response
    {
        $sortie = $entityManager->getRepository(Sortie::class)->find($id);

        //Quel est l'état de la sortie : ouverte!
        $ouvert = $sortie->getEtat()->getLibelle() === Etat::ouverte();

        if ($ouvert || $sortie->getEtat()->getLibelle() === Etat::cloturee()) {
            //enlever le participant de la liste
            $sortie->removeParticipant($this->getUser());

            if (count($sortie->getParticipants()) < $sortie->getNbInscriptionsMax() && $sortie->getDateLimiteInscription() > new \DateTime('now')) {
                $sortie->setEtat($er->findOneBy(['libelle' => Etat::ouverte()]));
            }
            $entityManager->persist($sortie);
            $entityManager->flush();
            $this->addFlash('success', 'Votre désistement à été enregistré');
        } else {
            $this->addFlash('error', 'Votre désistement n\'a pas pu être pris en compte');
        }

        return $this->redirectToRoute('main_home');
    }

    /**
     * @Route("/maj", name="accueil")
     */

    public function accueil(SortieRepository       $sortieRepository,
                            EtatRepository         $etatRepository,
                            EntityManagerInterface $entityManager): Response
    {
       // mise a jour des états des sorties au moment de la connexion utilisateur

        // définition des tableaux selon etat sortie
        $majSortie = $sortieRepository->MiseAJourEtat(
            $etatRepository->findOneBy(['libelle' => Etat::ouverte()]),
            $etatRepository->findOneBy(['libelle' => Etat::cloturee()]),
            $etatRepository->findOneBy(['libelle' => Etat::finie()]));

        foreach ($majSortie as $sortie) {

            $inscription = $sortie->getDateLimiteInscription() < new \DateTime('now');
            $finie = $sortie->getDateHeureDebut() < new \DateTime('now');
            $archive = $sortie->getDateHeureDebut()->add(new \DateInterval('P30D')) < (new \DateTime('now'));

            //on vérifie si il est cloturé, passé ET archivé
            if ($archive && $inscription && $finie) {
                $sortie->setEtat($etatRepository->findOneBy(['libelle' => Etat::archivee()]));
                $entityManager->persist($sortie);
                $entityManager->flush();
            }
            //sinon est il cloturé ET passé?
            else if ($inscription && $finie) {
                $sortie->setEtat($etatRepository->findOneBy(['libelle' => Etat::finie()]));
                $entityManager->persist($sortie);
                $entityManager->flush();
            }
            //est il cloturé?
            else if ($inscription) {
                $sortie->setEtat($etatRepository->findOneBy(['libelle' => Etat::cloturee()]));
                $entityManager->persist($sortie);
                $entityManager->flush();
            }

        }
        return $this->redirectToRoute("main_home");
    }


    /**
     * @Route ("/afficher/{id}", name="afficher")
     *
     */

    public function afficherSortie(SortieRepository $sortieRepository, $id)
    {

        $sortie = $sortieRepository->find($id);

        return $this->render('sortie/affichage.html.twig', ['sortie' => $sortie]);

    }


}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}
{% endblock %}

{% block body %}
    {% if app.user %}
        <div class="profil">

        </div>
        <main class="form-filtre text-center displayCreate">

            <div class="row text-center">
                <h3>Filtrer les sorties</h3>
            </div>

            {{ form_start(searchForm) }}

            <div class="form-group row align-items-center">
                {{ form_label(searchForm.campus, "Campus", {'label_attr' : {'class' : 'col-form-label col-md-2 '}}) }}

                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.campus, {'attr': {'class' : 'form-select '}}) }}
                </div>

                {{ form_label(searchForm.organisateur ,"Sorties dont je suis l'organisateur(trice)", {'label_attr' : {'class' : 'col-form-label col-md-2 '}}) }}
                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.organisateur , {'attr' : {'class' : 'custom-control-input'}}) }}
                </div>
            </div>

            <div class="form-group row align-items-center">
                {{ form_label(searchForm.search, "Rechercher" , {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}

                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.search, {'attr': {'class' : 'form-control'}}) }}
                </div>
                {{ form_label(searchForm.inscrit ,"Sorties auxquelles je suis inscrit(e)", {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}

                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.inscrit , {'attr' : {'class' : 'custom-control-input'}}) }}
                </div>
            </div>

            <div class="form-group row align-items-center">
                {{ form_label(searchForm.dateMin, "Entre le ", {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}

                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.dateMin, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                {{ form_label(searchForm.nonInscrit ,"Sorties auxquelles je ne suis pas inscrit(e)", {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}
                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.nonInscrit, {'attr' : {'class' : 'custom-control-input'}}) }}
                </div>
            </div>

            <div class="form-group row align-items-center">
                {{ form_label(searchForm.dateMax, "Et le ", {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}
                <div class="col-md-2 align-items-center">
                    {{ form_widget(searchForm.dateMax , {'attr' : {'class' : 'form-control'}}) }}
                </div>
                {{ form_label(searchForm.sortiePassee ,"Sorties passées", {'label_attr' : {'class' : 'col-form-label col-md-2'}}) }}
                <div class="col-md-2 align-items-center">

                    {{ form_widget(searchForm.sortiePassee , {'attr' : {'class' : 'custom-control-input'}}) }}
                </div>
            </div>

            <button class="btn btn-secondary text-center" type="submit">Rechercher</button>
            {{ form_end(searchForm) }}

        </main>

        <div class="card mb-4">
            <div class="table-responsive">
                <h2 class="card-title text-center">Liste des sorties</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Nom de la sortie</th>
                        <th>Date de la sortie</th>
                        <th class="hidden"> Lieu</th>
                        <th class="displayCreate">Clôture</th>
                        <th class="displayCreate">Inscrits/Places</th>
                        <th class="displayCreate">Etat</th>
                        <th class="displayCreate">Inscrit?</th>
                        <th class="displayCreate">Organisateur</th>
                        <th class="displayCreate">Action</th>
                    </tr>

                    </thead>
                    <tbody>
                    {% for sortie in sorties %}

                        <tr>
                            <td class="displayCreate">{{ sortie.nom }}</td>
                            <td class="hidden"><a
                                        href="{{ path( 'main_afficher', {'id': sortie.id} ) }}">{{ sortie.nom }}</a>
                            </td>
                            <td>{{ sortie.dateHeureDebut | date('d/m/Y H:i') }}</td>
                            <td class="hidden">{{ sortie.lieu.ville.nom }}</td>
                            <td class="displayCreate">{{ sortie.dateLimiteInscription | date('d/m/Y ') }}</td>
                            <td class="displayCreate">{{ sortie.participants | length }}
                                / {{ sortie.nbInscriptionsMax }}</td>
                            <td class="displayCreate">{{ sortie.etat.libelle }}</td>
                            <td class="displayCreate">
                                {% for s in app.user.sorties %}
                                    {% if s.id == sortie.id %}
                                        Oui
                                    {% endif %}
                                {% endfor %}</td>

                            <td class="displayCreate"><a
                                        href="{{ path('profil_profilParticipant', {'id':sortie.getOrganisateurSortie.id}) }}">{{ sortie.getOrganisateurSortie.pseudo }}</a>
                            </td>


                            <td class="displayCreate">

                                {# affichage du bouton Afficher détail #}
                                {% if sortie.etat.libelle != archivee() %}
                                    <a href="{{ path( 'main_afficher', {'id': sortie.id} ) }}" class="btn btn-secondary"
                                       role="button">
                                        Afficher

                                    </a>
                                {% endif %}

                                {# affichage du bouton s'inscrire si Ouvert et si non inscrit #}
                                {% if sortie.etat.libelle == ouverte() and app.user.sorties.contains(sortie) == false %}
                                    <a href="{{ path( 'main_sinscrire', {'id': sortie.id} ) }}"
                                       class="btn btn-secondary"
                                       role="button">
                                        S'inscrire
                                    </a>
                                {% endif %}

                                {# affichage du bouton se désinscrire si Ouvert et si Inscrit #}
                                {% for s in app.user.sorties %}
                                    {% if s.id == sortie.id %}
                                        {% if sortie.etat.libelle == ouverte() or sortie.etat.libelle == cloturee() %}
                                            <a href="{{ path( 'main_desinscription', {'id': sortie.id} ) }}"
                                               class="btn btn-secondary"
                                               role="button">
                                                Se Désinscrire
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}

                                {# affichage du bouton modifier si on est le createur et si l'etat est cree #}
                                {% if  creee()  == sortie.etat.libelle %}
                                    {% if sortie.getOrganisateurSortie.id == app.user.id %}
                                        <a href="{{ path( 'sortie_create', {'id': sortie.id} ) }}"
                                           class="btn btn-secondary"
                                           role="button">
                                            Modifier
                                        </a>
                                    {% endif %}
                                {% endif %}

                                {# affichage du bouton annuler si on est le createur et si etat ouvert et cloture #}
                                {% if sortie.getOrganisateurSortie.id == app.user.id or app.user.roles == ['ROLE_ADMIN'] %}
                                    {% if sortie.etat.libelle == ouverte() %}
                                        <a href="{{ path( 'sortie_cancel', {'id': sortie.id}) }}"
                                           class="btn btn-secondary"
                                           role="button">
                                            Annuler
                                        </a>
                                    {% elseif sortie.etat.libelle == cloturee() %}
                                        <a href="{{ path( 'sortie_cancel', {'id': sortie.id} ) }}"
                                           class="btn btn-secondary"
                                           role="button">
                                            Annuler
                                        </a>
                                    {% endif %}
                                {% endif %}


                                {# affichage du bouton annuler si on est le createur et si etat ouvert et cloture #}
                                {% if sortie.getOrganisateurSortie.id == app.user.id and sortie.etat.libelle == creee() %}
                                    <a href="{{ path( 'sortie_publier', {'id': sortie.id} ) }}"
                                       class="btn btn-secondary"
                                       role="button">
                                        Publier
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    {% else %}
        <p> Veuillez vous connecter : <a href="{{ path('main_home') }}">Connexion</a></p>
    {% endif %}

{% endblock %}